version: '3'
services:
  db:
    image: "mysql:5.7.27"
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_HOST=mysql"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=order_system"
  spring:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c "/wait && ./gradlew flywayClean flywayBaseline flywayMigrate generateJooq test bootRun -PenvironmentName=prod"
